# Stage 1: Build the application
FROM openjdk:17-jdk-alpine AS build
WORKDIR /app
COPY build/libs/muiu-0.0.1-SNAPSHOT.jar /app/app.jar

# Stage 2: Nginx + Spring Boot
FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/app.jar /app/app.jar
RUN apk add --no-cache openjdk17-jre supervisor
COPY supervisord.conf /etc/supervisord.conf

# 환경 변수 설정
ENV SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}
ENV SERVER_PORT=${SERVER_PORT}
ENV SPRING_DATASOURCE_DRIVER_CLASS_NAME=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
ENV SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
ENV SPRING_JPA_DATABASE=${SPRING_JPA_DATABASE}
ENV SPRING_JPA_DATABASE_PLATFORM=${SPRING_JPA_DATABASE_PLATFORM}
ENV SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
ENV SPRING_JPA_SHOW_SQL=${SPRING_JPA_SHOW_SQL}
ENV SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
ENV SMS_API_KEY=${SMS_API_KEY}
ENV SMS_API_SECRET_KEY=${SMS_API_SECRET_KEY}
ENV SMS_DOMAIN=${SMS_DOMAIN}
ENV SMS_FROM_NUMBER=${SMS_FROM_NUMBER}
ENV SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
ENV SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
ENV SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
ENV SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
ENV SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
ENV SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
ENV NAVER_CLIENTID=${NAVER_CLIENTID}
ENV NAVER_SECRETKEY=${NAVER_SECRETKEY}
ENV NCP_ACCESSKEY=${NCP_ACCESSKEY}
ENV NCP_SECRETKEY=${NCP_SECRETKEY}
ENV NCP_REGIONNAME=${NCP_REGIONNAME}
ENV NCP_ENDPOINT=${NCP_ENDPOINT}
ENV SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=10MB
ENV SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=100MB
ENV CLOVA_HOST=${CLOVA_HOST}
ENV CLOVA_API_KEY=${CLOVA_API_KEY}
ENV CLOVA_API_KEY_PRIMARY_VAL=${CLOVA_API_KEY_PRIMARY_VAL}
ENV CLOVA_REQUEST_ID=${CLOVA_REQUEST_ID}

EXPOSE 9090 80 443
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
